<?php
global $post;
if (!empty($items)):
    
    foreach ($items as $comment):
        
		?><tr>
            <td><a class="topicLink" href="<?php echo esc_attr(get_permalink($comment['post_id']) . 'topic/' . $comment['thread_id']);
            	?>"><?php if ($comment['resolved']): ?>[<?php echo CMDM_Labels::getLocalized('support_thread_resolved'); ?>] <?php endif; ?><?php
            	echo esc_html($comment['title']); ?></a></td>
            <td><?php echo $comment['counter']; ?></td>
            <td><?php echo $comment['lastPoster']; ?></td>
            <td><?php echo CMDM_SupportThread::renderDaysAgo($comment['lastUpdate'], true); ?>
            </td>
        </tr><?php
        
    endforeach;
    
else:

	?><tr><td colspan="4">
		<?php echo CMDM_Labels::getLocalized('support_no_topics'); ?>
		<?php  if ( is_user_logged_in() ) {
			echo ', ';
			echo CMDM_Labels::getLocalized('support_create_topic_call'); 
		} ?>
	</td></tr><?php

endif;
