<div class="wrap">
    <h2><?php _e('Import/Export', 'cm-download-manager'); ?></h2>
    <?php echo CMDM_BaseController::getAdminNav(); ?>
    <div class="clear"></div>
<h1>PRO plan offers:</h1>
<p style="font-size:16px; max-width:65%;">The Import and Export feature in CM Download Manager Pro simplifies managing digital downloads by allowing administrators to transfer files, settings, and metadata through CSV files. This ensures an organized process for bulk updates and site migrations.</p>
    <div style="float:left; width:100%; margin-bottom:30px;">
        <div style="text-align:center; width:500px; float:left; margin-right:20px;">
            <a href="<?php echo esc_attr(CMDM_URL . '/views/resources/imgs/cm-download-manager-import-and-export.png'); ?>" target="_blank" style="text-decoration:none;">
                <img src="<?php echo esc_attr(CMDM_URL . '/views/resources/imgs/cm-download-manager-import-and-export.png'); ?>" alt="" style="width:100%; border:1px solid #444;" />
            </a>
            <span style="font-size:15px;">Import and Export Dashboard</span>
        </div>
    </div>
<br>
<h3>Upgrade to Pro for:</h3>
<ul style="font-size:16px;">
    <li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Importing and exporting files, metadata, and settings using CSV files.</li>
    <li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Efficiently migrating download configurations between environments.</li>
    <li> <svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Managing large-scale content changes with precision and ease.</li>
</ul>
<br>
<a href="<?php echo admin_url('admin.php?page=cmdm_pro'); ?>" style="font-size: 16px; line-height: 20px; font-weight: 500; padding: 10px 30px; background-color: #008000; border-color: #008000; color: #fff; text-decoration:none;">Upgrade to Pro</a>
</div>