<div class="wrap">
    <h2><?php _e('User Groups', 'cm-download-manager'); ?></h2>
    <?php echo CMDM_BaseController::getAdminNav(); ?>
    <div class="clear"></div>
<h1>PRO plan offers:</h1>
<p style="font-size:16px; max-width:65%;">The User Groups feature in CM Download Manager Pro enhances access control by allowing administrators to assign permissions and restrictions to specific user groups. This ensures tailored visibility and management of digital downloads.</p>
    <div style="float:left; width:100%; margin-bottom:30px;">
        <div style="text-align:center; width:500px; float:left; margin-right:20px;">
            <a href="<?php echo esc_attr(CMDM_URL . '/views/resources/imgs/cm-download-manager-user-groups.png'); ?>" target="_blank" style="text-decoration:none;">
                <img src="<?php echo esc_attr(CMDM_URL . '/views/resources/imgs/cm-download-manager-user-groups.png'); ?>" alt="" style="width:100%; border:1px solid #444;" />
            </a>
            <span style="font-size:15px;">Managing User Groups</span>
        </div>
    </div>
<br>
<h3>Upgrade to Pro for:</h3>
<ul style="font-size:16px;">
    <li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Creating and managing custom user groups for file access.</li>
    <li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Restricting downloads to specific groups based on permissions.</li>
    <li> <svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Simplifying access control for larger, diverse user bases.</li>
</ul>
<br>
<a href="<?php echo admin_url('admin.php?page=cma_pro'); ?>" style="font-size: 16px; line-height: 20px; font-weight: 500; padding: 10px 30px; background-color: #008000; border-color: #008000; color: #fff; text-decoration:none;">Upgrade to Pro</a>
</div>