<div class="wrap">
    <h2><?php _e('CM Downloads Logs', 'cm-download-manager'); ?></h2>
    <?php echo CMDM_BaseController::getAdminNav(); ?>
    <div class="clear"></div>
<h1>PRO plan offers:</h1>
<p style="font-size:16px; max-width:65%;">The Logs feature in CM Download Manager Pro provides detailed tracking and reporting of all file downloads, helping administrators monitor user activity and download trends effectively.</p>
    <div style="float:left; width:100%; margin-bottom:30px;">
        <div style="text-align:center; width:350px; float:left; margin-right:20px;">
            <a href="<?php echo esc_attr(CMDM_URL . '/views/resources/imgs/cm-download-manager-logs-logs-records.png'); ?>" target="_blank" style="text-decoration:none;">
                <img src="<?php echo esc_attr(CMDM_URL . '/views/resources/imgs/cm-download-manager-logs-logs-records.png'); ?>" alt="" style="width:100%; border:1px solid #444;" />
            </a>
            <span style="font-size:15px;">Logs Records</span>
        </div>
        <div style="text-align:center; width:350px; float:left; margin-right:20px;">
            <a href="<?php echo esc_attr(CMDM_URL . '/views/resources/imgs/cm-download-manager-logs-show-graph.png'); ?>" target="_blank" style="text-decoration:none;">
                <img src="<?php echo esc_attr(CMDM_URL . '/views/resources/imgs/cm-download-manager-logs-show-graph.png'); ?>" alt="" style="width:100%; border:1px solid #444;" />
            </a>
            <span style="font-size:15px;">Graph View</span>
        </div>
    </div>
<br>
<h3>Upgrade to Pro for:</h3>
<ul style="font-size:16px;">
    <li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Accessing comprehensive logs for all file downloads, including timestamps, user details, and IP addresses.</li>
    <li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Exporting download logs as CSV files for further analysis and record-keeping.</li>
    <li> <svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Visualizing download trends through interactive graphs and insights.</li>
</ul>
<br>
<a href="<?php echo admin_url('admin.php?page=cmdm_pro'); ?>" style="font-size: 16px; line-height: 20px; font-weight: 500; padding: 10px 30px; background-color: #008000; border-color: #008000; color: #fff; text-decoration:none;">Upgrade to Pro</a>
</div>