<style type="text/css">
    .subsubsub li+li:before {content:'| ';}
</style>
<div id="CMDM_admin_nav">
<ul class="subsubsub">
    <?php
	foreach ($submenus as $menu) {
		if($menu['title'] != '<span class="cmseparator"></span>') {
			?>
			<li><a href="<?php echo $menu['link']; ?>" <?php echo ($menu['current'])?'class="current"':''; ?>><?php echo $menu['title']; ?></a></li>
			<?php
		}
	}
	?>
</ul>
<br class="clear" />
</div>