<?php
/**
 * @deprecated
 */


get_header(); ?>

<div class="CMDM site-content">
    <div class="CMDM-app">
        <div class="cmdm-main">
        
			<ul class="errors">
			<?php 
			foreach ($errors as $error): ?>
			    <li><?php echo $error; ?></li>
			
			<?php endforeach; ?>
			</ul>
			<a href="javascript:window.history.go(-1)"><?php echo CMDM_Labels::getLocalized('access_denied_go_back'); ?></a>
			
		</div>
	</div>
</div>

<?php get_footer(); ?>